# Generated by Django 5.1 on 2024-08-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tofficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.RemoveField(
            model_name='tofficer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='TOfficer',
        ),
    ]
