# Generated by Django 5.1 on 2024-08-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_city_remove_game_sport_delete_municipality_and_more'),
        ('teachers', '0004_alter_teacher_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='accounts.region'),
        ),
    ]
