# Generated by Django 5.1 on 2025-05-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('badge_name', models.CharField(max_length=100)),
                ('certificate_name', models.CharField(max_length=100)),
                ('school_institution', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Acting Principal', 'Acting Principal'), ('Deputy Principal', 'Deputy Principal'), ('Acting deputy principal', 'Acting deputy principal'), ('Retired principal', 'Retired principal'), ('Head of Department', 'Head of Department'), ('other', 'Other')], max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('registering_for', models.CharField(choices=[('council', 'ICP Council | August 25 - 28, 2025'), ('convention', 'ICP Convention | August 25 - 28, 2025'), ('combined', 'Combined ICP Council & ICP World Convention')], max_length=20)),
                ('is_icp_member', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dietary', models.CharField(choices=[('none', 'None'), ('gluten_free', 'Gluten-Free'), ('halal', 'Halal'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=20)),
                ('dietary_other', models.CharField(blank=True, max_length=100)),
                ('attend_cocktail', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('attend_dinner', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('bringing_accompanying_person', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer / EFT'), ('card', 'Credit Card')], max_length=10)),
                ('billing_company', models.CharField(max_length=255)),
                ('billing_contact_person', models.CharField(max_length=100)),
                ('billing_contact_number', models.CharField(max_length=20)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True)),
                ('accept_social_media', models.BooleanField(default=False)),
                ('popia_acknowledged', models.BooleanField(default=False)),
                ('share_info_with_delegates', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
