# Generated by Django 5.1 on 2025-06-05 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
