# Generated by Django 5.1 on 2025-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0002_conventionregistration_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventionregistration',
            name='attend_cocktail',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='attend_dinner',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='billing_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='billing_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='billing_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='billing_contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='bringing_accompanying_person',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='dietary',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('gluten_free', 'Gluten-Free'), ('halal', 'Halal'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='dietary_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer / EFT'), ('card', 'Credit Card')], max_length=10, null=True),
        ),
    ]
