# Generated by Django 5.1 on 2025-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0003_alter_conventionregistration_attend_cocktail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventionregistration',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
