# Generated by Django 5.1 on 2025-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0004_alter_conventionregistration_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventionregistration',
            name='registering_for',
            field=models.CharField(choices=[('council', 'ACP Council | August 25 - 28, 2025'), ('convention', 'ACP Convention | August 25 - 28, 2025'), ('combined', 'Combined ACP Council & ACP World Convention')], max_length=20),
        ),
    ]
